apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: labex-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

